server/lib/server_web/router.ex
defmodule ServerWeb.Router do
  use ServerWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", ServerWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)

    resources("/pull-requests", PullRequestController, only: [:index, :show]) do
      resources("/check-result-sets", CheckResultSetController, only: [:edit])
      resources("/check-results", CheckResultController, only: [:update])
    end
  end

  scope "/auth", ServerWeb do
    pipe_through(:browser)

    get("/:provider", AuthController, :request)
    get("/:provider/callback", AuthController, :callback)
    delete("/logout", AuthController, :delete)
  end

  scope "/api", ServerWeb.Api do
    pipe_through(:api)

    resources("/check-result-sets", CheckResultSetController, only: [:create])

    scope "/github", GitHub do
      post("/webhooks", WebhookController, :create)
    end
  end
end

server/lib/server/git_hub/pull_request.ex
defmodule Server.GitHub.PullRequest do
  use Ecto.Schema
  import Ecto.Changeset
  import Ecto.Query

  schema "pull_requests" do
    field(:github_id, :integer)
    field(:head_branch, :string)
    field(:base_branch, :string)
    belongs_to(:repository, Server.GitHub.Repository)
    has_many(:check_runs, Server.GitHub.CheckRun)

    timestamps()
  end

  @doc false
  def changeset(pull_request, attrs) do
    pull_request
    |> cast(attrs, [:github_id, :repository_id, :head_branch, :base_branch])
    |> assoc_constraint(:repository)
    |> validate_required([:github_id, :head_branch, :base_branch])
  end

  def for_user(query, %Server.Accounts.User{} = user) do
    for_user(query, user.id)
  end

  def for_user(query, user_id) do
    from(
      pr in query,
      join: r in assoc(pr, :repository),
      join: u in assoc(r, :users),
      where: u.id == ^user_id
    )
  end
end

server/lib/server_web/controllers/pull_request_controller.ex
defmodule ServerWeb.PullRequestController do
  use ServerWeb, :controller
  alias Server.{Repo}
  alias Server.GitHub.{PullRequest}
  import Ecto.Query

  plug(ServerWeb.RequireAuth)

  def index(conn, _params) do
    pull_requests =
      PullRequest
      |> PullRequest.for_user(get_current_user_id(conn))
      |> Repo.all()

    render(conn, "index.html", pull_requests: pull_requests)
  end

  def show(conn, %{"id" => id}) do
    pull_request =
      from(
        PullRequest,
        preload: [check_runs: :check_result_set]
      )
      |> PullRequest.for_user(get_current_user_id(conn))
      |> Repo.get(id)

    render(conn, "show.html", pull_request: pull_request)
  end
end

server/lib/server_web/views/pull_request_view.ex
defmodule ServerWeb.PullRequestView do
  use ServerWeb, :view
  def latest_sha(nil), do: nil
  def latest_sha(check_run), do: check_run.head_sha
end

server/lib/server_web/templates/pull_request/index.html.eex
<p>
  Total: <%= length(assigns.pull_requests) %>
</p>
<%= for pull_request <- assigns.pull_requests do %>
  <p><%= link "ID: #{pull_request.id}", to: pull_request_path(@conn, :show, pull_request.id) %></p>
<% end %>

server/lib/server_web/templates/pull_request/show.html.eex
<p>ID: <%= assigns.pull_request.id %></p>
<p>Latest SHA: <%= latest_sha(List.first(assigns.pull_request.check_runs)) %></p>
<ul>
  <%= for check_run <- assigns.pull_request.check_runs do %>
    <li>
      <%=
        link(
          "#{check_run.inserted_at}: #{check_run.head_sha}",
          to: pull_request_check_result_set_path(@conn, :edit, assigns.pull_request.id, check_run.check_result_set.id)
        )
      %>
    </li>
  <% end %>
</ul>