server/lib/server_web/router.ex
defmodule ServerWeb.Router do
  use ServerWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", ServerWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", HomeController, :index)

    resources("/pull-requests", PullRequestController, only: [:index, :show]) do
      resources("/check-result-sets", CheckResultSetController, only: [:edit])
      resources("/check-results", CheckResultController, only: [:update])
    end
  end

  scope "/auth", ServerWeb do
    pipe_through(:browser)

    get("/:provider", AuthController, :request)
    get("/:provider/callback", AuthController, :callback)
    delete("/logout", AuthController, :delete)
  end

  scope "/api", ServerWeb.Api do
    pipe_through(:api)

    resources("/check-result-sets", CheckResultSetController, only: [:create])

    scope "/github", GitHub do
      post("/webhooks", WebhookController, :create)
    end
  end
end

server/lib/server_web/views/layout_view.ex
defmodule ServerWeb.LayoutView do
  use ServerWeb, :view
  import ServerWeb.Helpers.Auth

  def current_user(conn) do
    get_current_user(conn)
  end
end

server/lib/server_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>LaunchList</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script async src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </head>

  <body>
    <div class="container js-Pjax">
      <header class="header">
        <a href="/" class="logo">
          <h1>LaunchList</h1>
        </a>
        <div class="side-nav">
          <%= if user = current_user(@conn) do %>
            <span>
              <%= user.email %>
              <%= link("(Sign out)", to: auth_path(@conn, :delete), method: :delete, class: "logout") %>
            </span>
          <% else %>
            <%= link("Login with GitHub", to: auth_path(@conn, :request, "github")) %>
          <% end %>
        </div>

      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
  </body>
</html>